services:
  node:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: node-container
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: always
    depends_on:
      db:
        condition: service_healthy
  react:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: react-container
    ports:
     - 3001:3001
    stdin_open: true
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata/
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: dsolgames
    ports:
     - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "dsolgames", "-U", "postgres" ]
      interval: 120s
      timeout: 5s
      retries: 5
    volumes:
     - ./server/database.sql:/docker-entrypoint-initdb.d/database.sql
     - ./server/pgdata:/var/lib/postgresql/pgdata